### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by xcatlkd** [janepark7/byteme-app#75]
Currently there is no error handling directed to the user.

This will include:
Non-unique username on signup
Bad username or password on login
File upload failures
etc.

**Comment by xcatlkd** [comment]
The server now sends these error responses to the client.
Need to implement styling to display to user.

**Comment by janepark7** [comment]
- Login is now closed! Needs styling. 

Open: 
- File upload failures
- need to work on non unique username for sign up
